# 06wk-2: Numpy (2)

최규빈  
2023-04-12

<a href="https://colab.research.google.com/github/guebin/PP2023/blob/main/posts/02_DataScience/2023-04-12-6wk-2.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" style="text-align: left"></a>

# 강의영상

> youtube:
> <https://youtube.com/playlist?list=PLQqh36zP38-z-L_OmVbSF6lmFbS9IfOsI>

# import

In [1]:
import numpy as np

# 넘파이 공부 4단계: 축

## np.concatenate

`-` 1차원: concat의 기본예제 (쓸모 없어보임)

In [145]:
a= np.array([1,2,3]) 
b= -a 

In [146]:
np.concatenate([a,b])

In [147]:
np.array(list(a)+list(b))

`-` 2차원: 이건 좀 의미가 있어보임

In [148]:
a = np.array([1,2,3,4]).reshape(2,2)
b = -a 

In [149]:
np.concatenate([a,b])

만약에 a,b를 좌우로 붙이고 싶다면? axis=1이라고 옵션을 주면 된다.

In [150]:
np.concatenate([a,b],axis=1) 

-   axis=1의 의미는 무엇일까?

`-` axis=1 의 의미를 파악하기 전에, axis=1만 가능한것인지 알아보자.

(시도1)

In [31]:
np.concatenate([a,b],axis=0)
# np.concatenate([a,b]) 와 같음 
# np.concatenate([a,b])은 np.concatenate([a,b],axis=0)의 생략버전이라 유추가능

-   axis=0 도 가능!!

(시도2)

In [33]:
np.concatenate([a,b],axis=2)
# 에러가 난다. 

-   axis=1은 불가능!!

`-` axis의 의미를 알아보자.

In [151]:
a= np.array([1,2,3,4,5,6]).reshape(3,2)
b= -a 

(예시1)

In [152]:
a.shape,b.shape, np.concatenate([a,b],axis=0).shape

-   관찰: `(3,2)` concat `(3,2)` -\> `(6,2)` // 첫번째 숫자가 바뀜 \<==
    axis=0

(예시2)

In [42]:
a.shape,b.shape, np.concatenate([a,b],axis=1).shape

-   관찰: `(3,2)` concat `(3,2)` -\> `(3,4)` // 두번째 숫자가 바뀜 \<==
    axis=1

(예시3)

In [154]:
a= np.arange(24).reshape(2,3,4) 
b= -a 

In [155]:
a.shape,b.shape,np.concatenate([a,b],axis=0).shape

-   유추: `(2,3,4)` concat `(2,3,4)` -\> `(4,3,4)` // 첫번째 숫자가 바뀔
    것 같았는데 실제로 그러함 \<== axis=0

(예시4)

In [156]:
a.shape,b.shape,np.concatenate([a,b],axis=1).shape

-   `(2,3,4)` concat `(2,3,4)` -\> `(2,6,4)` // 두번째 숫자가 바뀜 \<==
    axis=1

(예시5)

In [157]:
a.shape,b.shape,np.concatenate([a,b],axis=2).shape

-   `(2,3,4)` concat `(2,3,4)` -\> `(2,3,8)` // 세번째 숫자가 바뀜 \<==
    axis=2

(예시5)

In [158]:
a.shape,b.shape,np.concatenate([a,b],axis=-1).shape

-   `(2,3,4)` concat `(2,3,4)` -\> `(2,3,8)` // 마지막 숫자가 바뀜 \<==
    axis=-1

(예시6)

In [159]:
a.shape,b.shape,np.concatenate([a,b],axis=-2).shape

-   `(2,3,4)` concat `(2,3,4)` -\> `(2,6,4)` // 마지막에서 두번째 숫자가
    바뀜 \<== axis=-2

(예시7)

In [160]:
a.shape,b.shape,np.concatenate([a,b],axis=-3).shape

-   `(2,3,4)` concat `(2,3,4)` -\> `(4,3,4)` // 마지막에서 세번째 숫자가
    바뀜 \<== axis=-3

(예시8)

In [161]:
a.shape,b.shape,np.concatenate([a,b],axis=-4).shape

-   `(2,3,4)` concat `(2,3,4)` -\> `???` // 마지막에서 네번째 숫자는
    없어서 에러남 \<== axis=-4

(예시9)

In [162]:
a.shape,b.shape,np.concatenate([a,b],axis=3).shape

-   `(2,3,4)` concat `(2,3,4)` -\> `???` // 네번째 숫자는 없어서 에러남
    \<== axis=3

## np.stack

`-` 아래의 자료를 관찰하자.

In [3]:
a = np.array([1,2,3])
b = -a 

In [4]:
a,b

`-` 혹시 a,b를 위아래로 쌓아서 결과를 `(2,3)` 매트릭스로 만들 수 있을까?

In [7]:
np.concatenate([a,b]) # 실패1

In [9]:
np.concatenate([a,b],axis=1) # 실패2

`-` 실패이유를 분석: `(3,) concat (3,)` 으로 `(2,3)` 를 만들려고 해서
불가능했음.

-   전략: reshape을 이용하여 `(3,), (3,) => (1,3), (1,3)` 으로 변경후
    concat을 하면 가능할듯

In [11]:
np.concatenate([a.reshape(1,3),b.reshape(1,3)],axis=0) # 성공

또 다른 방법!

In [12]:
np.stack([a,b],axis=0)

`-` 이번에는 a,b를 좌우로 쌓아서 결과를 `(3,2)` 매트릭스로를 만들어
보자.

In [13]:
np.concatenate([a.reshape(3,1),b.reshape(3,1)],axis=1)

또 다른 방법!

In [14]:
np.stack([a,b],axis=1)

`-` 요약: stack은 `axis=` 위치에 축을 추가하고 concat을 한 것 이라
이해할 수 있다.

**강의에서는 하지 않은 예제**

In [166]:
a=np.arange(3*4*5).reshape(3,4,5) 
b=-a

In [167]:
a.shape, b.shape

In [170]:
np.stack([a,b],axis=0).shape # (3,4,5) => (1,3,4,5) // 첫 위치에 축이 추가되고 스택 

In [174]:
np.stack([a,b],axis=1).shape # (3,4,5) => (3,1,4,5) // 두번째 위치에 축이 추가되고 스택 

In [175]:
np.stack([a,b],axis=2).shape # (3,4,5) => (3,4,1,5) // 세번째 위치에 축이 추가되고 스택 

In [179]:
np.stack([a,b],axis=3).shape # (3,4,5) => (3,4,5,1) // 네번째 위치에 축이 추가되고 스택 

In [181]:
np.stack([a,b],axis=-1).shape # axis=-1 <=> axis=3 

In [182]:
np.stack([a,b],axis=-2).shape # axis=-2 <=> axis=2

***np.concatenate*** 는 축의 총 갯수를 유지하면서 결합, ***np.stack***은
축의 갯수를 하나 증가시키면서 결합

## sum

`-` 1차원 array의 sum

In [91]:
a = np.array([1,2,3,4])
a

In [92]:
a.sum()

In [93]:
np.sum(a)

`-` 2차원 array일 경우

In [95]:
a= np.arange(4*3).reshape(4,3)
a

In [101]:
a.sum(axis=-1)

-   마지막 축이 삭제됨

`-` 그렇다면?

In [104]:
a.sum(axis=(0,1))

-   첫번째 축과 두번째 축이 삭제됨

`-` 연습 (강의에서 하지 않은 예제)

In [197]:
a=np.array(range(10)).reshape(5,2) 
a

(문제1) 1열의 합, 2열의 합을 계산하고 싶다면?

(풀이) 차원이 (5,2) =\> (2,) 로 나와야 한다. (그럼 첫번째 축이
삭제되어야 하네?)

In [198]:
a.sum(axis=0)

(문제2) 1행의 합, 2행의 합, … , 5행의 합을 계산하고 싶다면?

(풀이) 차원이 (5,2) =\> (5,)로 나와야 한다. (그럼 두번째 축이 삭제되어야
하네?)

In [199]:
a.sum(axis=1)

(문제3) a의 모든원소의 합을 계산하고 싶다면?

(풀이) 차원이 (5,2) =\> () 로 나와야 한다. (첫번째축, 두번째축이 모두
삭제되어야 하네?)

In [201]:
a.sum(axis=(0,1))

In [203]:
a.sum() # 즉 a.sum(axis=(0,1))이 디폴트값임 

## mean, std, max, min, prod

`-` mean, std, max, min, prod 모두 sum과 유사한 논리임

`-` 평균

In [106]:
a = np.arange(3*5*5).reshape(3,5,5)
a

In [109]:
a.mean(axis=0)

-   `(3,5,5) => (5,5)`

In [111]:
a.mean(axis=(1,2))

-   `(3,5,5) => (3,)`

`-` std

In [17]:
a = np.array([1,2,3,4,5,6]).reshape(3,2)
a

In [18]:
a.std(axis=1)

**참고: 분모를 $n$이 아니라 $n-1$로 나누고 싶다면 아래와 같이
사용하라.**

In [19]:
a.std(axis=1,ddof=1)

`-` max,min,prod

In [20]:
a = np.array([1,2,3,4,5,6]).reshape(3,2)
a

In [21]:
a.max(axis=1)

In [22]:
a.min(axis=1)

In [23]:
a.prod(axis=1)

## argmax, argmin

`-` 아래와 같은 행렬 `a`를 고려하자.

In [25]:
a = np.random.rand(15).reshape(5,3)
a = np.stack([np.array(l)/l.sum() for l in a]) # 리스트는 5개의 원소가 있으며 각 원소는 차원이 (3,) => stack을 이용해 첫 위치에 축을 추가하여 (5,3) 매트릭스를 만듬 
a

-   편의상 이 행렬의 each-row 는 어떠한 이미지가 ‘개,고양이,사과’ 일
    확률을 의미한다고 상상하자.

`-` 위의 `a`에서 최대값을 가지는 index를 리턴하는 함수 (=`np.argmax`)를
행별로 적용하려면?

In [26]:
np.argmax(a,axis=1)

# HW

`1` – `6`. a,b가 아래와 같이 주어졌다고 하자.

In [3]:
a=np.array([1]*10)
b=np.array([2]*10)

`1`. a,b와 np.concatenate를 이용하여 아래와 같은 배열을 만들어라. //
2022-중간고사-1-(25)

    array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

(풀이)

In [5]:
np.concatenate([a,b])

`2`. a,b와 np.concatenate를 이용하여 아래와 같은 배열을 만들어라. //
2022-중간고사-1-(26)

In [6]:
a=np.array([1]*10)
b=np.array([2]*10)

    array([[1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2]])

(풀이)

In [8]:
np.concatenate([a.reshape(10,1),b.reshape(10,1)],axis=0)

`3`. a,b와 np.concatenate를 이용하여 아래와 같은 배열을 만들어라. //
2022-중간고사-1-(27)

    array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
           [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]

(풀이)

In [18]:
np.concatenate([a.reshape(1,10),b.reshape(1,10)],axis=0)

`4`. a,b와 np.concatenate를 이용하여 아래와 같은 배열을 만들어라. //
2022-중간고사-1-(28)

    array([[1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2]])

(풀이)

In [19]:
np.concatenate([a.reshape(10,1),b.reshape(10,1)],axis=1)

`5`. a,b와 np.stack을 이용하여 아래와 같은 배열을 만들어라. //
2022-중간고사-1-(29)

    array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
           [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]

(풀이)

In [23]:
np.stack([a,b],axis=0)

`6`. a,b와 np.stack을 이용하여 아래와 같은 배열을 만들어라. //
2022-중간고사-1-(30)

    array([[1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2]])

(풀이)

In [24]:
np.stack([a,b],axis=1)

**`7`–`10`**

아래와 같은 매트릭스를 생성하라.

In [25]:
np.random.seed(43052)
a=np.random.randn(10000).reshape(100,100)
a

`7`. 각 행의 합을 구하라. 즉 1행의 합, 2행의 합, … 100행의 합을
계산하라. // 2022-중간고사-2-(11)

-   1행의합 = 0.38342049 + 1.0841745 + … + 1.18701443

(풀이)

In [27]:
a.sum(axis=1)

`8`. `7`의 결과로 나온 배열의 표준편차를 구하라. // 2022-중간고사-1-(12)

(풀이)

In [28]:
a.sum(axis=1).std(ddof=1)

> `a.sum(axis=1).std()` 역시 정답으로 인정

`9`. 각 열의 평균을 구하라. 즉 1열의 평균, 2열의 평균, … , 100열의
평균을 계산하라. // 2022-중간고사-1-(13)

(풀이)

In [29]:
a.sum(axis=0)

`10`. `9`의 결과로 나온 배열의 표준편차를 구하라. //
2022-중간고사-1-(14)

(풀이)

In [30]:
a.sum(axis=0).std(ddof=1)

> `a.sum(axis=0).std()` 역시 정답으로 인정